# ID Twoich zasobów (weź je ze swojego starego kodu .gs)
calendar_id = "gdujescisko@gmail.com"
sheet_id = "1KEQcTzVS-88ZGt0lN2l7nudIul0bMWW53kGp8cP42UM"

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1KEQcTzVS-88ZGt0lN2l7nudIul0bMWW53kGp8cP42UM"
type = "service_account"
project_id = "wozki-473519"
private_key_id = "769b80721607ac300bcc31412171bb31bf858f99"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDIF/LrCt4rdjBc\nT3luEUNdF1SwXIa7+fuh5E5ho0mfxOfVwxk7rOgtxVSOFwI9aSHGMdhNNvmhU8t+\n9YWEiJVVQssbTnpof8sRY3I0wSYXbY2iWE+sYIKFCwMXmfp11DEut8uxK1Zpk9AH\nsBGQ9yScsjY4tSX+3CbAIPvzE3j8W2ly/kdUJ7zAGuLxzpVMyyOGmVpXgVEH1tn6\nlcF+GU4Qwxun/rIJZ+GQRruMZuYXUK24/GE//l/zAU+HUES4SpLezgcYtGX/EFoT\n1SAHTn10DnSN8pVIMLTlV6NEGr6pqKQ5l2pG8G+IF5V+oH0BpPpbadonD71UGqg3\n4Tar78GpAgMBAAECggEADwvfUaBmwNg+3mTVifAqDiEtK6Pm4nzJA3gCaDeErPXR\nbyggHiDW8WuCJmXW3nJTlAP3MtCRqKQp9xk/BI6BbZYREDPFuFT1Grt31j1jVWYA\nvWFXAGyIyWNgxKYTXkfqDjbLo5N8My07z/rZSfrjrxV8RqW3Po551X8azcERmyb2\n/RXdUEWqQRhOSL790CbjjGaUK/G8oj3YbUGBCXNKmq2j74nH1QXCJObbQ76bMmyp\nbBppA4Mx7CBV5zJkL9f/eTKKExde6TTnwOvsf6erHheNqGRoO3mfybUS06FjrAEp\nAKFbUb5LOrK2wLuvd7WsSeovv6VOfxDLlF64gEqeDwKBgQD99II2f70z7jX2zdbB\naxPoLa7Aco/69hHZnSsPEISnR8gtk+YhfM0AIP4LtyyXpXb4IksbVgE200pZTGh9\nvC4JQYIGcESd8Jps8GVZWQAWRfYGs1ZhOqbIGoNtPySa5L96Q+eKiJMH2ydLiICm\nuY4snyRD7aItQ7tBvWDBCbbx9wKBgQDJtGmapROtysqyIZBxW6zXP8SOLeFMTfwr\nFeG1QvER3YMiy3JMyXAlaCHzxf80B0gCB/qN+eiD7289YtzdromS3AEJ4Vr1pN0G\nQ3GSiAfNcuOwzpBcnJs31C2FscRVX++Yoi6XSDCYFMyuqX1N0MLZkOOo2N2YSWlv\nixDTMDYBXwKBgAqeEmOc65gkOXVcHcJwa6ClaEz7fTGM4Cos/APhOOqVgbUGHfUA\ndsGun3B19BNTA6pUJLe73MkiBFW/cA7xsysH5hvGzdecm5g6ZMJbijlkK2kUTmQ6\nQ4bSNPR4U1t2fNrrw95y31LQws/RoS9XSq5q6OU+Ji2mS0nwVP89HLz5AoGAM7vD\nLjfSwUt3C5MSQhDaVubzGeholbKWz9Iv7ta5j/R5ku4NZeZwjheURbrtxsFrVaII\nQGvtmBFMPblinrUKchFdbtRPCRv82INp2MRtA+PIxGtmmWpNYVdZSaYbji4p/ML0\nIjcQx6DmEpJEIjY+E6FW0tK0mz+Q/Fv1t8TwxQ8CgYEAvGoY2BroppCk6VdK4V8Q\niz0S/lCqo3m9WvpjR+hQQ3dGe1mDXTerirN8VoluZyQ2BRv+HJ1cGA1Y25tpSNqh\nAmzmc8AKY4ah5esef5gkGFqsN7JIuuNC6DZATqeOqU7kwFvwi/EV1RGvv2yx0tCH\nKLPK7pQdjsRjJNwd8WP3tcU=\n-----END PRIVATE KEY-----\n"
client_email = "service-account@wozki-473519.iam.gserviceaccount.com"
client_id = "100158168989625190973"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-account%40wozki-473519.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[email]
sender_address = "wozkiujesciskowschod@gmail.com"
app_password = "qihm efsg ltmu brro"
smtp_server = "smtp.gmail.com"
smtp_port = 465